

import React, { useState, useMemo } from 'react'
import {
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Package,
  Plus,
  Edit,
  Trash2,
  X,
  AlertTriangle,
  Save,
  RefreshCw,
  Download,
} from 'lucide-react'
import ExportButton from '../ExportButton'

const MaintenanceProfile = () => {
const [stockData] = useState([
  {
    id: 1,
    siteId: 'JBC12',
    siteName: 'Tulip',
    unitName: 'Urban',
    unitType: 'E',
    sqtfeetArea: '1000',
    sqtfeetRate: '2000',
    balance: '200',
    openingDateTime: '2025-08-01 10:30 AM',
  },
  {
    id: 2,
    siteId: 'JBC54321',
    siteName: 'Rosewood',
    unitName: 'Garden',
    unitType: 'R',
    sqtfeetArea: '1200',
    sqtfeetRate: '2200',
    balance: '350',
    openingDateTime: '2025-08-02 02:15 PM',
  },
  {
    id: 3,
    siteId: 'JBC11223',
    siteName: 'Sunview',
    unitName: 'Tower A',
    unitType: 'C',
    sqtfeetArea: '950',
    sqtfeetRate: '1800',
    balance: '120',
    openingDateTime: '2025-08-05 09:45 AM',
  },
  {
    id: 4,
    siteId: 'JBC66778',
    siteName: 'GreenField',
    unitName: 'Block B',
    unitType: 'E',
    sqtfeetArea: '1350',
    sqtfeetRate: '2500',
    balance: '500',
    openingDateTime: '2025-08-10 04:20 PM',
  },
  {
    id: 5,
    siteId: 'JBC88990',
    siteName: 'LakeView',
    unitName: 'Wing C',
    unitType: 'R',
    sqtfeetArea: '1100',
    sqtfeetRate: '2100',
    balance: '275',
    openingDateTime: '2025-08-15 11:10 AM',
  },
])


  // State management
  const [searchTerm, setSearchTerm] = useState('')
  const [categoryFilter, setCategoryFilter] = useState('all')
  const [currentPage, setCurrentPage] = useState(1)
  const [itemsPerPage, setItemsPerPage] = useState(5)
  const [sortConfig, setSortConfig] = useState({ key: null, direction: 'asc' })
  const [stock, setStock] = useState(stockData)

  // Modal states
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [selectedItem, setSelectedItem] = useState(null)

  // Form state
  const [formData, setFormData] = useState({
    siteId: '',
    siteName: '',
    unitName: '',
    sqtfeetArea: '',
    sqtfeetRate: '',
    openingDateTime: '',
  })

  // Handle form input changes
  const handleInputChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }))
  }

  // Reset form
  const resetForm = () => {
    setFormData({
      siteId: '',
      siteName: '',
      unitName: '',
      sqtfeetArea: '',
      sqtfeetRate: '',
      openingDateTime: '',
    })
  }

  // Handle Add Product
  const handleAddProduct = () => {
    setShowAddModal(true)
    resetForm()
  }

  const submitAdd = () => {
    if (formData.productName && formData.quantity) {
      const newProduct = {
        id: Date.now(), // In real app, this would be generated by backend
        productName: formData.productName,
        productDetails: formData.productDetails,
        quantity: parseInt(formData.quantity),
        category: formData.category,
        minStockLevel: parseInt(formData.minStockLevel) || 0,
      }
      setStock((prev) => [...prev, newProduct])
      setShowAddModal(false)
      resetForm()
    }
  }

  // Handle Edit Product
  const handleEditProduct = (item) => {
    setSelectedItem(item)
    setFormData({
      siteId: item?.siteId,
      siteName: item?.siteName,
      unitName: item?.unitName,
      sqtfeetArea: item?.sqtfeetArea,
      sqtfeetRate: item?.sqtfeetRate,
      openingDateTime: item?.openingDateTime,
    })
    setShowEditModal(true)
  }

  const submitEdit = () => {
    if (selectedItem && formData.productName && formData.quantity) {
      setStock((prev) =>
        prev.map((item) =>
          item.id === selectedItem.id
            ? {
                ...item,
                siteId: formData?.siteId,
                siteName: formData?.siteName,
                unitName: formData?.unitName,
                sqtfeetArea: formData?.sqtfeetArea,
                sqtfeetRate: formData?.sqtfeetRate,
                openingDateTime: formData?.openingDateTime,
              }
            : item,
        ),
      )
      setShowEditModal(false)
      setSelectedItem(null)
      resetForm()
    }
  }

  // Handle Delete Product
  const handleDeleteProduct = (item) => {
    setSelectedItem(item)
    setShowDeleteModal(true)
  }

  const confirmDelete = () => {
    if (selectedItem) {
      setStock((prev) => prev.filter((item) => item.id !== selectedItem.id))
    }
    setShowDeleteModal(false)
    setSelectedItem(null)
  }

  // Close modals
  const closeModals = () => {
    setShowAddModal(false)
    setShowEditModal(false)
    setShowDeleteModal(false)
    setSelectedItem(null)
    resetForm()
  }

  // Filtered and sorted data
  const filteredAndSortedData = useMemo(() => {
    let filtered = stock.filter((item) => {
      const matchesSearch =
        item?.siteId.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item?.siteName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item?.sqtfeetArea.toLowerCase().includes(searchTerm.toLowerCase())

      const matchesCategory = categoryFilter === 'all' || item.category === categoryFilter

      return matchesSearch && matchesCategory
    })

    // Sort data
    if (sortConfig.key) {
      filtered.sort((a, b) => {
        if (a[sortConfig.key] < b[sortConfig.key]) {
          return sortConfig.direction === 'asc' ? -1 : 1
        }
        if (a[sortConfig.key] > b[sortConfig.key]) {
          return sortConfig.direction === 'asc' ? 1 : -1
        }
        return 0
      })
    }

    return filtered
  }, [stock, searchTerm, categoryFilter, sortConfig])

  // Pagination
  const totalPages = Math.ceil(filteredAndSortedData.length / itemsPerPage)
  const startIndex = (currentPage - 1) * itemsPerPage
  const paginatedData = filteredAndSortedData.slice(startIndex, startIndex + itemsPerPage)



  return (
    <div className="bg-white">
      {/* Add/Edit Modal */}
      {(showAddModal || showEditModal) && (
        <div className="fixed  inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 max-w-md w-full mx-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <Package className="w-6 h-6 text-blue-500 mr-3" />
                <h3 className="text-lg font-semibold text-gray-900">
                  {showAddModal ? 'Add New Customer' : 'Edit Customer'}
                </h3>
              </div>
              <button onClick={closeModals} className="text-gray-400 hover:text-gray-600">
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">JBCare ID *</label>
                <input
                  type="text"
                  name="siteId"
                  value={formData?.siteId}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter JBCare ID"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">ELM ID *</label>
                <input
                  type="text"
                  name="siteName"
                  value={formData?.siteName}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter ELM ID"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Connection No *
                </label>
                <input
                  type="text"
                  name="unitName"
                  value={formData?.unitName}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter Connection No"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Meter No *</label>
                <input
                  type="text"
                  name="sqtfeetArea"
                  value={formData?.sqtfeetArea}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter Meter No"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Opening Reading
                </label>
                <input
                  type="number"
                  name="sqtfeetRate"
                  value={formData?.sqtfeetRate}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter Opening Reading"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Opening Date & Time
                </label>
                <input
                  type="datetime-local"
                  name="openingDateTime"
                  value={formData?.openingDateTime}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div className="flex justify-end space-x-3 mt-6">
              <button
                onClick={closeModals}
                className="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={showAddModal ? submitAdd : submitEdit}
                className="px-6 py-2 bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors flex items-center"
              >
                <Save className="w-4 h-4 mr-2" />
                {showAddModal ? 'Add ' : 'Update '}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {showDeleteModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 max-w-md w-full mx-4">
            <div className="flex items-center mb-4">
              <AlertTriangle className="w-6 h-6 text-red-500 mr-3" />
              <h3 className="text-lg font-semibold text-gray-900">Confirm Delete</h3>
            </div>

            <p className="text-gray-600 mb-6">
              {selectedItem && <>Are you sure you want to delete ? This action cannot be undone.</>}
            </p>

            <div className="flex justify-end space-x-3">
              <button
                onClick={closeModals}
                className="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={confirmDelete}
                className="px-6 py-2 bg-red-600 text-white font-medium hover:bg-red-700 transition-colors"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-200">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Maintenance  Management</h2>
            <p className="text-gray-600 mt-1">Manage Maintenance Customers</p>
          </div>
          <div className="flex items-center space-x-3">
            <ExportButton data={stock} fileName="StockInData.xlsx" sheetName="Stock" />
            {/* <button
              onClick={handleAddProduct}
              className="bg-green-600 text-white px-4 py-2 hover:bg-green-700 transition-colors flex items-center"
            >
              <Plus className="w-4 h-4 mr-2" />
              Add Customer
            </button> */}
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="px-6 py-4 border-b border-gray-200">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Search */}
          <div className="md:col-span-2">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
              <input
                type="text"
                placeholder="Search..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 w-full border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
               Site Id
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
               Site Name
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Unit Name
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Unit Type
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                SqFeet Area
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Rate
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Opening Balance
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Opening Date
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Actions
              </th>
            </tr>
          </thead>

          <tbody className="bg-white divide-y divide-gray-200">
            {paginatedData?.map((item) => (
              <tr key={item.id} className="hover:bg-gray-50">
                <td className="px-6 py-4">{item?.siteId}</td>
                <td className="px-6 py-4">{item?.siteName}</td>
                <td className="px-6 py-4">{item?.unitName}</td>
                <td className="px-6 py-4">{item?.unitType}</td>
                <td className="px-6 py-4">{item?.sqtfeetArea}</td>
                <td className="px-6 py-4">{item?.sqtfeetRate}</td>
                <td className="px-6 py-4">₹{item?.balance}</td>
                <td className="px-6 py-4">{item?.openingDateTime}</td>
                <td className="px-6 py-4">
                  <div className="flex space-x-2">
                    <button
                      onClick={() => handleEditProduct(item)}
                      className="text-blue-600 hover:text-blue-800"
                    >
                      <Edit className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => handleDeleteProduct(item)}
                      className="text-red-600 hover:text-red-800"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <div className="px-6 py-4 border-t border-gray-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <span className="text-sm text-gray-700">Show:</span>
              <select
                value={itemsPerPage}
                onChange={(e) => {
                  setItemsPerPage(Number(e.target.value))
                  setCurrentPage(1)
                }}
                className="border border-gray-300 px-3 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value={5}>5</option>
                <option value={10}>10</option>
                <option value={25}>25</option>
                <option value={50}>50</option>
              </select>
              <span className="text-sm text-gray-700">per page</span>
            </div>
            <div className="text-sm text-gray-700">
              Showing {startIndex + 1} to{' '}
              {Math.min(startIndex + itemsPerPage, filteredAndSortedData.length)} of{' '}
              {filteredAndSortedData.length} results
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={() => setCurrentPage((prev) => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className="px-3 py-1 border border-gray-300 text-sm hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
            >
              <ChevronLeft className="w-4 h-4 mr-1" />
              Previous
            </button>

            <div className="flex space-x-1">
              {[...Array(Math.min(totalPages, 5))].map((_, index) => {
                const pageNumber =
                  currentPage <= 3
                    ? index + 1
                    : currentPage >= totalPages - 2
                      ? totalPages - 4 + index
                      : currentPage - 2 + index

                if (pageNumber < 1 || pageNumber > totalPages) return null

                return (
                  <button
                    key={pageNumber}
                    onClick={() => setCurrentPage(pageNumber)}
                    className={`px-3 py-1 text-sm border ${
                      currentPage === pageNumber
                        ? 'bg-blue-600 text-white border-blue-600'
                        : 'border-gray-300 hover:bg-gray-50'
                    }`}
                  >
                    {pageNumber}
                  </button>
                )
              })}
            </div>

            <button
              onClick={() => setCurrentPage((prev) => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages}
              className="px-3 py-1 border border-gray-300 text-sm hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
            >
              Next
              <ChevronRight className="w-4 h-4 ml-1" />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MaintenanceProfile
